// default package
// Generated 11 nov. 2014 10:10:09 by Hibernate Tools 3.4.0.CR1
package model;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name = "commande", catalog = "simple_app")
public class Commande implements java.io.Serializable {

	private Integer idcommande;
	private String intitulecommande;

	public Commande() {
	}

	public Commande(String intitulecommande) {
		this.intitulecommande = intitulecommande;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idcommande", unique = true, nullable = false)
	public Integer getIdcommande() {
		return this.idcommande;
	}

	public void setIdcommande(Integer idcommande) {
		this.idcommande = idcommande;
	}

	@Column(name = "intitulecommande", nullable = false, length = 50)
	public String getIntitulecommande() {
		return this.intitulecommande;
	}

	public void setIntitulecommande(String intitulecommande) {
		this.intitulecommande = intitulecommande;
	}

}
