package model;
// default package
// Generated 11 nov. 2014 10:10:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetailId generated by hbm2java
 */
@Embeddable
public class DetailId implements java.io.Serializable {

	private int idclient;
	private int idcommande;
	private Date date;

	public DetailId() {
	}

	public DetailId(int idclient, int idcommande, Date date) {
		this.idclient = idclient;
		this.idcommande = idcommande;
		this.date = date;
	}

	@Column(name = "idclient", nullable = false)
	public int getIdclient() {
		return this.idclient;
	}

	public void setIdclient(int idclient) {
		this.idclient = idclient;
	}

	@Column(name = "idcommande", nullable = false)
	public int getIdcommande() {
		return this.idcommande;
	}

	public void setIdcommande(int idcommande) {
		this.idcommande = idcommande;
	}

	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetailId))
			return false;
		DetailId castOther = (DetailId) other;

		return (this.getIdclient() == castOther.getIdclient())
				&& (this.getIdcommande() == castOther.getIdcommande())
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null
						&& castOther.getDate() != null && this.getDate()
						.equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdclient();
		result = 37 * result + this.getIdcommande();
		result = 37 * result
				+ (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

}
