package model;
// default package
// Generated 11 nov. 2014 10:10:09 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Detail generated by hbm2java
 */
@Entity
@Table(name = "detail", catalog = "simple_app")
public class Detail implements java.io.Serializable {

	private DetailId id;

	public Detail() {
	}

	public Detail(DetailId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idclient", column = @Column(name = "idclient", nullable = false)),
			@AttributeOverride(name = "idcommande", column = @Column(name = "idcommande", nullable = false)),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false, length = 10)) })
	public DetailId getId() {
		return this.id;
	}

	public void setId(DetailId id) {
		this.id = id;
	}

}
